import type { RouteAnnotations } from '@/types/annotation'

export const ROUTE_ANNOTATIONS: RouteAnnotations[] = [
  // ── Dashboard ──
  {
    route: '/dashboard',
    pageTitle: 'Dashboard',
    pageDescription: 'The advisor\'s morning command center — AI-prioritized actions, live metrics, and contextual intelligence in one view.',
    annotations: [
      {
        id: 'dash-metrics',
        number: 1,
        title: 'Live Practice Metrics',
        description: 'A compact metrics strip that summarizes AUM, flows, meetings, and pending actions at a glance. Each metric is clickable, navigating directly to the relevant section of the app.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'dash-ai-insights',
        number: 2,
        title: 'AI-Generated Insights',
        description: 'Proactive intelligence from the AI engine — surfacing portfolio risks, market opportunities, and client events without the advisor having to ask. Purple accent marks all AI-generated content throughout the app.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'dash-nba',
        number: 3,
        title: 'Next Best Actions Feed',
        description: 'AI-scored and prioritized action items. Each NBA has a composite score blending urgency, client value, and impact. Actions link directly to the execution screen — one click from insight to action.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'dash-schedule',
        number: 4,
        title: 'Today\'s Schedule',
        description: 'Upcoming meetings with one-click prep — opens a meeting workspace with agenda, talking points, and AI briefing. Demonstrates context-aware workflow: the AI knows which client you\'re about to see.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'dash-ai-toggle',
        number: 5,
        title: 'AI Assistant Toggle',
        description: 'Opens the AI chat panel (Ctrl+J). The assistant is context-aware — it knows which page you\'re on, which client you\'re viewing, and adapts its suggestions accordingly. Also accessible via keyboard shortcut.',
        theme: 'ai_embedded',
        anchor: 'bottom-left',
      },
      {
        id: 'dash-search',
        number: 6,
        title: 'Universal Search (Ctrl+K)',
        description: 'Command palette that searches across clients, accounts, households, pages, and actions. Type ">" to access quick actions like "Rebalance" or "New Client." Designed for keyboard-first advisors.',
        theme: 'actionable_ux',
        anchor: 'bottom-right',
      },
    ],
  },

  // ── Actions / NBA Center ──
  {
    route: '/actions',
    pageTitle: 'Actions Center',
    pageDescription: 'The AI-powered action queue — every pending task is scored, grouped for batch processing, and linked to its execution screen.',
    annotations: [
      {
        id: 'actions-feed',
        number: 1,
        title: 'NBA Feed',
        description: 'A prioritized feed of Next Best Actions generated by the AI engine. Each card shows the action, the affected client, estimated impact, and a direct execution link. Sorted by composite urgency+value score.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'actions-batch',
        number: 2,
        title: 'Batch Action Banner',
        description: 'When 2+ clients need the same action (e.g., rebalancing after a model drift), the system groups them into a batch. One click processes all affected accounts together — 10x faster than handling individually.',
        theme: 'batch_actions',
        anchor: 'top-right',
      },
      {
        id: 'actions-card',
        number: 3,
        title: 'Actionable NBA Card',
        description: 'Each card is a direct-action surface: "Execute" links to the right screen (trade ticket, rebalance wizard, tax harvester), "Delegate" hands off to the AI, and "Dismiss" removes it with reason tracking.',
        theme: 'actionable_ux',
        anchor: 'center-right',
      },
      {
        id: 'actions-tabs',
        number: 4,
        title: 'Effectiveness Analytics',
        description: 'The "Effectiveness" tab tracks which NBAs were acted on, time-to-action, and revenue impact. Closes the loop: the AI learns from advisor behavior to improve future prioritization.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'actions-filters',
        number: 5,
        title: 'Multi-Axis Filtering',
        description: 'Filter by category (rebalancing, tax, risk...), priority, and urgency simultaneously. Sort by priority score or urgency countdown. Helps advisors focus on what matters most right now.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Client Detail ──
  {
    route: '/clients/:clientId',
    pageTitle: 'Client Detail',
    pageDescription: 'A 360° client view with embedded AI intelligence, workflow launchers, and collaborative sharing — all without leaving the page.',
    annotations: [
      {
        id: 'client-ai-summary',
        number: 1,
        title: 'AI Client Summary',
        description: 'An always-visible AI-generated synopsis: AUM, risk profile, goal probability, and any at-risk flags. The purple left border is the system\'s visual language for "AI wrote this" — consistent across every screen.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'client-workflow',
        number: 2,
        title: 'Workflow Launch Button',
        description: 'One-click access to start any workflow (account opening, ACAT transfer, compliance review) pre-filled with this client\'s data. Eliminates context-switching between CRM and workflow systems.',
        theme: 'smart_workflows',
        anchor: 'center-left',
      },
      {
        id: 'client-insights',
        number: 3,
        title: 'Contextual AI Insights',
        description: 'AI insights specific to this client — concentration risk, tax-loss harvesting opportunities, upcoming RMDs, or service alerts. These update dynamically as the client\'s portfolio changes.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'client-share',
        number: 4,
        title: 'Share with Team/AI',
        description: 'Rich card sharing — send a client summary card to the AI assistant ("What should I discuss with this client?") or to a team member via the messaging panel. No copy-paste needed.',
        theme: 'actionable_ux',
        anchor: 'center-left',
      },
      {
        id: 'client-notes',
        number: 5,
        title: 'Tabbed Workspace',
        description: 'Overview, Accounts, Planning, Documents, Activity, and Notes — each tab is a focused view. Notes support AI-generated entries (purple accent). The tab layout is consistent across all entity pages.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Trading ──
  {
    route: '/portfolios/trading',
    pageTitle: 'Trading Desk',
    pageDescription: 'Multi-asset trade entry supporting 5 asset classes with AI market intelligence, smart validation, and class-specific fields.',
    annotations: [
      {
        id: 'trading-ai-insights',
        number: 1,
        title: 'AI Market Intelligence',
        description: 'Real-time AI insights for trading: market conditions, wash sale warnings, concentration alerts. The AI proactively flags risks before you submit an order — like having a junior analyst watching over your shoulder.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'trading-asset-class',
        number: 2,
        title: 'Multi-Asset Class Selector',
        description: 'Switch between Equity, Options, Mutual Funds, Fixed Income, and Digital Assets. Each class has tailored fields: Greeks display for options, NAV info for funds, yield metrics for bonds, 24h data for crypto.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'trading-tabs',
        number: 3,
        title: 'Single vs. Model Trade',
        description: 'Single trade for individual orders, Model trade for applying changes across all accounts in a model. The model trade multiplies efficiency: one decision propagates to dozens of accounts.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'trading-summary',
        number: 4,
        title: 'Smart Order Summary',
        description: 'Live order preview with estimated cost, commission, and validation status. Updates as you fill in fields. Pre-fill support from AI suggestions means the advisor often just reviews and submits.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'trading-orders',
        number: 5,
        title: 'Recent Orders Blotter',
        description: 'A live view of today\'s orders with status tracking (pending → submitted → filled). Provides immediate feedback loop: you can verify an order was processed without switching to the OMS.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Workflows ──
  {
    route: '/workflows',
    pageTitle: 'Workflow Center',
    pageDescription: 'Operational command center — human tasks, AI-delegated tasks, process pipelines, and workflow templates in one place.',
    annotations: [
      {
        id: 'workflows-tabs',
        number: 1,
        title: 'Four Workflow Views',
        description: 'My Actions (personal tasks), In-Process (SLA-tracked pipelines with NIGO flagging), Delegated (AI agent tasks running autonomously), and Templates (one-click workflow launch). Each view serves a different operational need.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'workflows-ai-status',
        number: 2,
        title: 'AI Task Monitor',
        description: 'Live counter of AI agents working autonomously — document generation, compliance checks, data gathering. The advisor delegates, the AI executes, and the results appear in the Delegated tab.',
        theme: 'ai_embedded',
        anchor: 'center-left',
      },
    ],
  },

  // ── Households ──
  {
    route: '/households',
    pageTitle: 'Household Hub',
    pageDescription: 'Family-level aggregation with AI insights, sortable household data, and click-through to 360° household views.',
    annotations: [
      {
        id: 'hh-ai-insights',
        number: 1,
        title: 'AI Household Insights',
        description: 'AI-generated intelligence at the household level — asset location opportunities, family-wide risk exposure, and cross-account optimization suggestions. Purple accent marks all AI-generated content.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'hh-table',
        number: 2,
        title: 'Household Table',
        description: 'Sortable household list showing aggregated AUM, account count, member count, and household-level status. Each row is clickable, navigating to the full household detail view.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'hh-nav',
        number: 3,
        title: 'Household Detail Navigation',
        description: 'Click through to a 360° household view with consolidated portfolio, family tree, member accounts, and household-level AI briefings.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
    ],
  },

  // ── Growth Pipeline ──
  {
    route: '/growth',
    pageTitle: 'Growth Pipeline',
    pageDescription: 'Sales pipeline management with Kanban board, prospect metrics, and AI-powered proposal generation.',
    annotations: [
      {
        id: 'growth-metrics',
        number: 1,
        title: 'Pipeline Metrics Strip',
        description: 'Four KPIs at a glance: total prospects, total pipeline AUM, probability-weighted pipeline value, and average close probability. Updates dynamically as prospects move through stages.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'growth-health',
        number: 2,
        title: 'Pipeline Health KPIs',
        description: 'Operational health metrics: average days in current stage, win rate (prospects reaching onboarding), and pipeline velocity (weighted AUM per day). Helps identify bottlenecks in the sales process.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'growth-view-toggle',
        number: 3,
        title: 'Board / List Toggle',
        description: 'Switch between Kanban board (visual pipeline stages) and sortable list view. Board view shows cards grouped by stage; list view provides a data-dense table with 8 sortable columns.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'growth-prospect-actions',
        number: 4,
        title: 'Prospect Action Buttons',
        description: 'Context-sensitive actions on each prospect card: "Generate Proposal" (AI-powered, purple accent) appears in the Proposal stage, "Start Onboarding" appears in the Onboarding stage. One click from pipeline to execution.',
        theme: 'ai_embedded',
        anchor: 'center-right',
      },
    ],
  },

  // ── Revenue / Practice Management ──
  {
    route: '/growth/revenue',
    pageTitle: 'Revenue Analytics',
    pageDescription: 'Practice-level revenue tracking with fee schedules, trend analysis, and tier-based client segmentation.',
    annotations: [
      {
        id: 'revenue-metrics',
        number: 1,
        title: 'Revenue Metrics',
        description: 'Key financials: Total Recurring Revenue, MTD and YTD revenue, and Year-over-Year growth rate. Provides an immediate health check on the advisory practice.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'revenue-trend',
        number: 2,
        title: 'Revenue Trend Chart',
        description: 'Monthly revenue line chart with an AI-projected overlay (purple dashed line). Actual vs. projected comparison helps identify revenue trajectory and potential shortfalls before they materialize.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'revenue-segment',
        number: 3,
        title: 'Segment Breakdown',
        description: 'Revenue broken down by client tier (Platinum, Gold, Silver, Bronze). Color-coded bar chart + data table shows revenue concentration and household count per segment — essential for capacity planning.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
    ],
  },

  // ── Engage ──
  {
    route: '/engage',
    pageTitle: 'Client Engagement',
    pageDescription: 'Unified communication hub with email composition, call logging, campaign management, and AI-drafted content tracking.',
    annotations: [
      {
        id: 'engage-actions',
        number: 1,
        title: 'Communication Actions',
        description: 'One-click entry points for Compose Email and Log Call — the two most common advisor communication tasks. Each opens a focused dialog without leaving the engagement context.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'engage-ai-drafted',
        number: 2,
        title: 'AI-Drafted Indicator',
        description: 'The purple sparkle icon marks communications drafted by the AI assistant. This visual language is consistent across the entire app — every AI-generated artifact carries the purple accent.',
        theme: 'ai_embedded',
        anchor: 'center-right',
      },
      {
        id: 'engage-campaigns',
        number: 3,
        title: 'Campaign Management',
        description: 'Status-driven campaign cards showing audience size, send count, open rate, and click rate. Campaign lifecycle flows from Draft → Scheduled → Active → Completed with appropriate action buttons at each stage.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'engage-tabs',
        number: 4,
        title: 'Multi-Channel Tabs',
        description: 'Four communication channels in one view: Client Comms (email/phone/video history), Campaigns (bulk outreach), Social (LinkedIn/Twitter content), and Newsletters. Unified engagement without switching tools.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Portfolios ──
  {
    route: '/portfolios',
    pageTitle: 'Portfolio Overview',
    pageDescription: 'Multi-view portfolio management with real-time drift monitoring, batch rebalancing, and model-based portfolio grouping.',
    annotations: [
      {
        id: 'portfolio-view-toggle',
        number: 1,
        title: 'Three Portfolio Views',
        description: 'Accounts, Households, and Models — three different lenses on the same data. Households show family-level aggregation with expandable sub-accounts. Models show drift across all accounts sharing a strategy.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'portfolio-drift',
        number: 2,
        title: 'Real-Time Drift Monitor',
        description: 'Every account shows its drift from the target model. Red flags indicate accounts needing rebalance. Toggle "Drifted only" to focus on what needs attention — filter down to just the accounts that need action.',
        theme: 'smart_workflows',
        anchor: 'center-left',
      },
      {
        id: 'portfolio-rebalance',
        number: 3,
        title: 'One-Click Trade Access',
        description: 'Direct navigation to the multi-asset trading desk. Select drifted accounts from the table, then "Rebalance N accounts" batch-processes them through the rebalance wizard. From detection to action in two clicks.',
        theme: 'batch_actions',
        anchor: 'center-left',
      },
    ],
  },
]
