import type { RouteAnnotations } from '@/types/annotation'

export const ROUTE_ANNOTATIONS: RouteAnnotations[] = [
  // ── Dashboard ──
  {
    route: '/dashboard',
    pageTitle: 'Dashboard',
    pageDescription: 'The advisor\'s morning command center — AI-prioritized actions, live metrics, and contextual intelligence in one view.',
    annotations: [
      {
        id: 'dash-metrics',
        number: 1,
        title: 'Live Practice Metrics',
        description: 'A compact metrics strip that summarizes AUM, flows, meetings, and pending actions at a glance. Each metric is clickable, navigating directly to the relevant section of the app.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'dash-ai-insights',
        number: 2,
        title: 'AI-Generated Insights',
        description: 'Proactive intelligence from the AI engine — surfacing portfolio risks, market opportunities, and client events without the advisor having to ask. Purple accent marks all AI-generated content throughout the app.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'dash-nba',
        number: 3,
        title: 'Next Best Actions Feed',
        description: 'AI-scored and prioritized action items. Each NBA has a composite score blending urgency, client value, and impact. Actions link directly to the execution screen — one click from insight to action.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'dash-schedule',
        number: 4,
        title: 'Today\'s Schedule',
        description: 'Upcoming meetings with one-click prep — opens a meeting workspace with agenda, talking points, and AI briefing. Demonstrates context-aware workflow: the AI knows which client you\'re about to see.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'dash-ai-toggle',
        number: 5,
        title: 'AI Assistant Toggle',
        description: 'Opens the AI chat panel (Ctrl+J). The assistant is context-aware — it knows which page you\'re on, which client you\'re viewing, and adapts its suggestions accordingly. Also accessible via keyboard shortcut.',
        theme: 'ai_embedded',
        anchor: 'bottom-left',
      },
      {
        id: 'dash-search',
        number: 6,
        title: 'Universal Search (Ctrl+K)',
        description: 'Command palette that searches across clients, accounts, households, pages, and actions. Type ">" to access quick actions like "Rebalance" or "New Client." Designed for keyboard-first advisors.',
        theme: 'actionable_ux',
        anchor: 'bottom-right',
      },
    ],
  },

  // ── Actions / NBA Center ──
  {
    route: '/actions',
    pageTitle: 'Actions Center',
    pageDescription: 'The AI-powered action queue — every pending task is scored, grouped for batch processing, and linked to its execution screen.',
    annotations: [
      {
        id: 'actions-feed',
        number: 1,
        title: 'NBA Feed',
        description: 'A prioritized feed of Next Best Actions generated by the AI engine. Each card shows the action, the affected client, estimated impact, and a direct execution link. Sorted by composite urgency+value score.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'actions-batch',
        number: 2,
        title: 'Batch Action Banner',
        description: 'When 2+ clients need the same action (e.g., rebalancing after a model drift), the system groups them into a batch. One click processes all affected accounts together — 10x faster than handling individually.',
        theme: 'batch_actions',
        anchor: 'top-right',
      },
      {
        id: 'actions-card',
        number: 3,
        title: 'Actionable NBA Card',
        description: 'Each card is a direct-action surface: "Execute" links to the right screen (trade ticket, rebalance wizard, tax harvester), "Delegate" hands off to the AI, and "Dismiss" removes it with reason tracking.',
        theme: 'actionable_ux',
        anchor: 'center-right',
      },
      {
        id: 'actions-tabs',
        number: 4,
        title: 'Effectiveness Analytics',
        description: 'The "Effectiveness" tab tracks which NBAs were acted on, time-to-action, and revenue impact. Closes the loop: the AI learns from advisor behavior to improve future prioritization.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'actions-filters',
        number: 5,
        title: 'Multi-Axis Filtering',
        description: 'Filter by category (rebalancing, tax, risk...), priority, and urgency simultaneously. Sort by priority score or urgency countdown. Helps advisors focus on what matters most right now.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Client Detail ──
  {
    route: '/clients/:clientId',
    pageTitle: 'Client Detail',
    pageDescription: 'A 360° client view with embedded AI intelligence, workflow launchers, and collaborative sharing — all without leaving the page.',
    annotations: [
      {
        id: 'client-ai-summary',
        number: 1,
        title: 'AI Client Summary',
        description: 'An always-visible AI-generated synopsis: AUM, risk profile, goal probability, and any at-risk flags. The purple left border is the system\'s visual language for "AI wrote this" — consistent across every screen.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'client-workflow',
        number: 2,
        title: 'Workflow Launch Button',
        description: 'One-click access to start any workflow (account opening, ACAT transfer, compliance review) pre-filled with this client\'s data. Eliminates context-switching between CRM and workflow systems.',
        theme: 'smart_workflows',
        anchor: 'center-left',
      },
      {
        id: 'client-insights',
        number: 3,
        title: 'Contextual AI Insights',
        description: 'AI insights specific to this client — concentration risk, tax-loss harvesting opportunities, upcoming RMDs, or service alerts. These update dynamically as the client\'s portfolio changes.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'client-share',
        number: 4,
        title: 'Share with Team/AI',
        description: 'Rich card sharing — send a client summary card to the AI assistant ("What should I discuss with this client?") or to a team member via the messaging panel. No copy-paste needed.',
        theme: 'actionable_ux',
        anchor: 'center-left',
      },
      {
        id: 'client-notes',
        number: 5,
        title: 'Tabbed Workspace',
        description: 'Overview, Accounts, Planning, Documents, Activity, and Notes — each tab is a focused view. Notes support AI-generated entries (purple accent). The tab layout is consistent across all entity pages.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Trading ──
  {
    route: '/portfolios/trading',
    pageTitle: 'Trading Desk',
    pageDescription: 'Multi-asset trade entry supporting 5 asset classes with AI market intelligence, smart validation, and class-specific fields.',
    annotations: [
      {
        id: 'trading-ai-insights',
        number: 1,
        title: 'AI Market Intelligence',
        description: 'Real-time AI insights for trading: market conditions, wash sale warnings, concentration alerts. The AI proactively flags risks before you submit an order — like having a junior analyst watching over your shoulder.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'trading-asset-class',
        number: 2,
        title: 'Multi-Asset Class Selector',
        description: 'Switch between Equity, Options, Mutual Funds, Fixed Income, and Digital Assets. Each class has tailored fields: Greeks display for options, NAV info for funds, yield metrics for bonds, 24h data for crypto.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'trading-tabs',
        number: 3,
        title: 'Single vs. Model Trade',
        description: 'Single trade for individual orders, Model trade for applying changes across all accounts in a model. The model trade multiplies efficiency: one decision propagates to dozens of accounts.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'trading-summary',
        number: 4,
        title: 'Smart Order Summary',
        description: 'Live order preview with estimated cost, commission, and validation status. Updates as you fill in fields. Pre-fill support from AI suggestions means the advisor often just reviews and submits.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
      {
        id: 'trading-orders',
        number: 5,
        title: 'Recent Orders Blotter',
        description: 'A live view of today\'s orders with status tracking (pending → submitted → filled). Provides immediate feedback loop: you can verify an order was processed without switching to the OMS.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },

  // ── Workflows ──
  {
    route: '/workflows',
    pageTitle: 'Workflow Center',
    pageDescription: 'Operational command center — human tasks, AI-delegated tasks, process pipelines, and workflow templates in one place.',
    annotations: [
      {
        id: 'workflows-tabs',
        number: 1,
        title: 'Four Workflow Views',
        description: 'My Actions (personal tasks), In-Process (SLA-tracked pipelines with NIGO flagging), Delegated (AI agent tasks running autonomously), and Templates (one-click workflow launch). Each view serves a different operational need.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'workflows-ai-status',
        number: 2,
        title: 'AI Task Monitor',
        description: 'Live counter of AI agents working autonomously — document generation, compliance checks, data gathering. The advisor delegates, the AI executes, and the results appear in the Delegated tab.',
        theme: 'ai_embedded',
        anchor: 'center-left',
      },
    ],
  },

  // ── Portfolios ──
  {
    route: '/portfolios',
    pageTitle: 'Portfolio Overview',
    pageDescription: 'Multi-view portfolio management with real-time drift monitoring, batch rebalancing, and model-based portfolio grouping.',
    annotations: [
      {
        id: 'portfolio-view-toggle',
        number: 1,
        title: 'Three Portfolio Views',
        description: 'Accounts, Households, and Models — three different lenses on the same data. Households show family-level aggregation with expandable sub-accounts. Models show drift across all accounts sharing a strategy.',
        theme: 'actionable_ux',
        anchor: 'top-right',
      },
      {
        id: 'portfolio-drift',
        number: 2,
        title: 'Real-Time Drift Monitor',
        description: 'Every account shows its drift from the target model. Red flags indicate accounts needing rebalance. Toggle "Drifted only" to focus on what needs attention — filter down to just the accounts that need action.',
        theme: 'smart_workflows',
        anchor: 'center-left',
      },
      {
        id: 'portfolio-rebalance',
        number: 3,
        title: 'One-Click Trade Access',
        description: 'Direct navigation to the multi-asset trading desk. Select drifted accounts from the table, then "Rebalance N accounts" batch-processes them through the rebalance wizard. From detection to action in two clicks.',
        theme: 'batch_actions',
        anchor: 'center-left',
      },
    ],
  },

  // ── Settings ──
  {
    route: '/settings',
    pageTitle: 'Settings',
    pageDescription: 'Control center for AI behavior, automation rules, templates, NBA tuning, and display preferences — the advisor tailors the system to their workflow.',
    annotations: [
      {
        id: 'settings-autonomy',
        number: 1,
        title: 'AI Autonomy Controls',
        description: 'Standing rules, permission matrix, and delegation configuration. Define what the AI can do autonomously (auto-approve), what needs review (queue), and what requires explicit sign-off (hold). Granular per-action control.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
      {
        id: 'settings-templates',
        number: 2,
        title: 'Template Library',
        description: 'Editable email and document templates with {{variable}} placeholders. Live preview resolves sample data so you see exactly what the AI will generate. Templates feed into AI draft actions across the app.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'settings-alert-rules',
        number: 3,
        title: 'Custom Alert Rules',
        description: 'Natural-language rule builder: "When [drift] [exceeds] [5%] for [any client], generate [high] NBA." Dropdown-driven sentence construction makes complex alert logic accessible without code.',
        theme: 'ai_embedded',
        anchor: 'top-left',
      },
    ],
  },

  // ── Household Detail ──
  {
    route: '/households/:householdId',
    pageTitle: 'Household Detail',
    pageDescription: 'Family-level view aggregating accounts, positions, allocation, and drift across all household members — the natural unit for wealth planning.',
    annotations: [
      {
        id: 'household-family-tree',
        number: 1,
        title: 'Family Tree',
        description: 'Visual representation of household members with click-through to individual client profiles. Shows relationships and makes it easy to navigate between family members during planning conversations.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'household-goals',
        number: 2,
        title: 'Goals & Allocation',
        description: 'Consolidated allocation chart aggregated across all household accounts, paired with financial goal progress cards. Shows the household-level asset mix and how it maps to each goal\'s probability of success.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'household-drift',
        number: 3,
        title: 'Household Drift',
        description: 'Per-account drift summary with a "Rebalance Household" button that pre-selects all drifted accounts in the rebalance wizard. Batch-rebalance an entire family in one action instead of account by account.',
        theme: 'batch_actions',
        anchor: 'top-left',
      },
    ],
  },

  // ── Account Detail ──
  {
    route: '/portfolios/accounts/:accountId',
    pageTitle: 'Account Detail',
    pageDescription: 'Deep-dive workspace for a single account — allocation, positions, drift, performance, risk, concentration, and order history across 6 tabs.',
    annotations: [
      {
        id: 'account-tabs',
        number: 1,
        title: 'Multi-Tab Workspace',
        description: 'Six focused views: Overview (allocation + drift + AI insight), Positions (with inline buy/sell), Performance (growth chart + benchmark), Risk (factors + stress tests), Concentration (treemap + breach detection), Orders (blotter).',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'account-drift',
        number: 2,
        title: 'Drift & Rebalance',
        description: 'Real-time drift card with per-asset-class breakdown (target vs. actual). Red left border when above threshold. "Rebalance Now" button navigates directly to the rebalance wizard pre-loaded with this account.',
        theme: 'smart_workflows',
        anchor: 'top-right',
      },
      {
        id: 'account-concentration',
        number: 3,
        title: 'Concentration Analysis',
        description: 'D3 treemap visualization of position weights with HHI (Herfindahl) index calculation. Automatically flags IPS breaches when any position or sector exceeds defined limits. Compliance-aware risk monitoring.',
        theme: 'ai_embedded',
        anchor: 'top-right',
      },
    ],
  },

  // ── Engage ──
  {
    route: '/engage',
    pageTitle: 'Engage',
    pageDescription: 'Unified client outreach hub — communications log, campaign management, social media scheduling, and newsletters with compliance tracking.',
    annotations: [
      {
        id: 'engage-comms',
        number: 1,
        title: 'Client Communications',
        description: 'Filterable log of all client communications across channels (email, phone, video, in-person, letter) with direction tracking. AI-generated messages are marked with the purple sparkle. Compose and log directly from here.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'engage-campaigns',
        number: 2,
        title: 'Campaign Management',
        description: 'Create and manage multi-channel campaigns with audience sizing, open/click rate tracking, and compliance approval status. NBA-triggered campaigns are flagged with purple badges. Draft → Schedule → Active → Completed lifecycle.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
    ],
  },

  // ── Prospects / Growth Pipeline ──
  {
    route: '/growth',
    pageTitle: 'Growth Pipeline',
    pageDescription: 'Prospect pipeline management with Kanban board, list view, pipeline analytics, and stage-specific actions — from lead to onboarding.',
    annotations: [
      {
        id: 'prospects-metrics',
        number: 1,
        title: 'Pipeline Analytics',
        description: 'Three key pipeline health metrics: average days in stage (velocity indicator), win rate (conversion efficiency), and pipeline velocity (weighted AUM throughput per day). Quick health check on the growth engine.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
      {
        id: 'prospects-board',
        number: 2,
        title: 'Pipeline Board',
        description: 'Kanban view with 5 stages (Lead → Discovery → Proposal → Decision → Onboarding). Board/List toggle switches between visual pipeline and sortable data table. Each column shows stage AUM and prospect count.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'prospects-actions',
        number: 3,
        title: 'Stage-Aware Actions',
        description: 'Prospect cards surface context-specific actions: "Generate Proposal" appears in the Proposal stage (purple, AI-powered), "Start Onboarding" in the Onboarding stage. Phone and email buttons on every card.',
        theme: 'ai_embedded',
        anchor: 'center-right',
      },
    ],
  },

  // ── Revenue / Practice Management ──
  {
    route: '/growth/revenue',
    pageTitle: 'Practice Management',
    pageDescription: 'Revenue analytics, team activity tracking, and book-of-business insights — the advisor\'s practice health dashboard with segment-level drill-down.',
    annotations: [
      {
        id: 'book-segments',
        number: 1,
        title: 'Client Segmentation',
        description: 'AUM breakdown by tier (platinum, gold, silver, bronze) with color-coded charts and tables. Shows concentration of revenue across segments — helps identify where growth opportunities and retention risks live.',
        theme: 'smart_workflows',
        anchor: 'top-left',
      },
      {
        id: 'book-growth',
        number: 2,
        title: 'Growth Trends',
        description: '12-month client growth trend showing new clients, attrition, and net new. Top growth households table links directly to household detail pages. Tracks organic growth momentum.',
        theme: 'actionable_ux',
        anchor: 'top-left',
      },
    ],
  },
]
